# Matrix opeation using python

## Types of Matrices

In [1]:
import numpy as np

# Example: Creating Different Types of Matrices

# Square Matrix
square_matrix = np.array([[1, 2], [3, 4]])
print("Square Matrix:\n", square_matrix)

# Diagonal Matrix
diagonal_matrix = np.diag([1, 2, 3])
print("Diagonal Matrix:\n", diagonal_matrix)

# Identity Matrix
identity_matrix = np.eye(3)
print("Identity Matrix:\n", identity_matrix)

# Zero Matrix
zero_matrix = np.zeros((2, 3))
print("Zero Matrix:\n", zero_matrix)

Square Matrix:
 [[1 2]
 [3 4]]
Diagonal Matrix:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]
Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Zero Matrix:
 [[0. 0. 0.]
 [0. 0. 0.]]


## Matrix Arithmetic

In [2]:
# Matrix Addition
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = A + B
print("Matrix Addition:\n", C)

# Matrix Subtraction
D = A - B
print("Matrix Subtraction:\n", D)

# Scalar Multiplication
scalar = 2
E = scalar * A
print("Scalar Multiplication:\n", E)

# Matrix Multiplication
F = np.dot(A, B)
print("Matrix Multiplication:\n", F)

# Element-wise Multiplication
G = A * B
print("Element-wise Multiplication:\n", G)

Matrix Addition:
 [[ 6  8]
 [10 12]]
Matrix Subtraction:
 [[-4 -4]
 [-4 -4]]
Scalar Multiplication:
 [[2 4]
 [6 8]]
Matrix Multiplication:
 [[19 22]
 [43 50]]
Element-wise Multiplication:
 [[ 5 12]
 [21 32]]


## Matrix Properties

In [3]:
# Transpose of a Matrix
A = np.array([[1, 2], [3, 4]])
A_transpose = A.T
print("Transpose of Matrix A:\n", A_transpose)

# Symmetric Matrix
symmetric_matrix = np.array([[1, 2, 3], [2, 4, 5], [3, 5, 6]])
print("Symmetric Matrix:\n", symmetric_matrix)

# Skew-Symmetric Matrix
skew_symmetric_matrix = np.array([[0, -2, 1], [2, 0, -4], [-1, 4, 0]])
print("Skew-Symmetric Matrix:\n", skew_symmetric_matrix)

# Determinant of a Matrix
determinant = np.linalg.det(A)
print("Determinant of Matrix A:", determinant)

# Inverse of a Matrix
inverse_A = np.linalg.inv(A)
print("Inverse of Matrix A:\n", inverse_A)

Transpose of Matrix A:
 [[1 3]
 [2 4]]
Symmetric Matrix:
 [[1 2 3]
 [2 4 5]
 [3 5 6]]
Skew-Symmetric Matrix:
 [[ 0 -2  1]
 [ 2  0 -4]
 [-1  4  0]]
Determinant of Matrix A: -2.0000000000000004
Inverse of Matrix A:
 [[-2.   1. ]
 [ 1.5 -0.5]]


## pecial Matrices

In [4]:
# Identity Matrix
identity_matrix = np.eye(3)
print("Identity Matrix:\n", identity_matrix)

# Diagonal Matrix
diagonal_matrix = np.diag([1, 2, 3])
print("Diagonal Matrix:\n", diagonal_matrix)

# Orthogonal Matrix
Q = np.array([[1, 0], [0, -1]])
print("Orthogonal Matrix:\n", Q)
print("Q^T Q:\n", np.dot(Q.T, Q))

# Sparse Matrix
from scipy.sparse import csr_matrix

sparse_matrix = csr_matrix([[1, 0, 0], [0, 0, 3], [4, 0, 0]])
print("Sparse Matrix:\n", sparse_matrix)
print("Dense Representation of Sparse Matrix:\n", sparse_matrix.todense())

Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Diagonal Matrix:
 [[1 0 0]
 [0 2 0]
 [0 0 3]]
Orthogonal Matrix:
 [[ 1  0]
 [ 0 -1]]
Q^T Q:
 [[1 0]
 [0 1]]
Sparse Matrix:
 <Compressed Sparse Row sparse matrix of dtype 'int64'
	with 3 stored elements and shape (3, 3)>
  Coords	Values
  (0, 0)	1
  (1, 2)	3
  (2, 0)	4
Dense Representation of Sparse Matrix:
 [[1 0 0]
 [0 0 3]
 [4 0 0]]


## Matrix Decomposition

In [5]:
# LU Decomposition
from scipy.linalg import lu

A = np.array([[4, 3], [6, 3]])
P, L, U = lu(A)
print("LU Decomposition:\nP:\n", P, "\nL:\n", L, "\nU:\n", U)

# QR Decomposition
Q, R = np.linalg.qr(A)
print("QR Decomposition:\nQ:\n", Q, "\nR:\n", R)

# Cholesky Decomposition
B = np.array([[4, 2], [2, 2]])
L = np.linalg.cholesky(B)
print("Cholesky Decomposition:\n", L)

# Eigen Decomposition
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

# Singular Value Decomposition (SVD)
U, S, VT = np.linalg.svd(A)
print("Singular Value Decomposition:\nU:\n", U, "\nS:\n", S, "\nVT:\n", VT)

LU Decomposition:
P:
 [[0. 1.]
 [1. 0.]] 
L:
 [[1.         0.        ]
 [0.66666667 1.        ]] 
U:
 [[6. 3.]
 [0. 1.]]
QR Decomposition:
Q:
 [[-0.5547002  -0.83205029]
 [-0.83205029  0.5547002 ]] 
R:
 [[-7.21110255 -4.16025147]
 [ 0.         -0.83205029]]
Cholesky Decomposition:
 [[2. 0.]
 [1. 1.]]
Eigenvalues:
 [ 7.77200187+0.j -0.77200187+0.j]
Eigenvectors:
 [[ 0.62246561+0.j -0.53222953+0.j]
 [ 0.78264715+0.j  0.8466001 +0.j]]
Singular Value Decomposition:
U:
 [[-0.59581566 -0.80312122]
 [-0.80312122  0.59581566]] 
S:
 [8.33557912 0.71980602] 
VT:
 [[-0.86400595 -0.50348159]
 [ 0.50348159 -0.86400595]]


## Solving Linear Systems

In [6]:
# Gaussian Elimination
from scipy.linalg import solve

A = np.array([[3, 2], [1, 2]])
b = np.array([5, 5])
x = solve(A, b)
print("Solution using Gaussian Elimination:\n", x)

# Matrix Inversion Method
A_inv = np.linalg.inv(A)
x = np.dot(A_inv, b)
print("Solution using Matrix Inversion:\n", x)

# Using LU Decomposition
P, L, U = lu(A)
y = np.linalg.solve(L, np.dot(P.T, b))
x = np.linalg.solve(U, y)
print("Solution using LU Decomposition:\n", x)

# Iterative Methods (Jacobi)
def jacobi(A, b, x0, tol=1e-10, max_iterations=100):
    x = x0
    D = np.diag(A)
    R = A - np.diagflat(D)
    for _ in range(max_iterations):
        x_new = (b - np.dot(R, x)) / D
        if np.linalg.norm(x_new - x) < tol:
            break
        x = x_new
    return x

x0 = np.zeros_like(b)
x_jacobi = jacobi(A, b, x0)
print("Solution using Jacobi Iterative Method:\n", x_jacobi)

Solution using Gaussian Elimination:
 [2.96059473e-16 2.50000000e+00]
Solution using Matrix Inversion:
 [4.4408921e-16 2.5000000e+00]
Solution using LU Decomposition:
 [2.96059473e-16 2.50000000e+00]
Solution using Jacobi Iterative Method:
 [0.  2.5]


## Matrix Calculus

In [10]:
!python3 -m pip install sympy
import sympy as sp

# Define a square matrix A and a column vector x
A = sp.Matrix([[sp.Symbol('a11'), sp.Symbol('a12')], [sp.Symbol('a21'), sp.Symbol('a22')]])
x = sp.Matrix([sp.Symbol('x1'), sp.Symbol('x2')])

# Define the expression x^T * A * x
expr = x.T * A * x

# Compute the derivative with respect to x
derivative = sp.Matrix([sp.diff(expr[0], x[i]) for i in range(x.shape[0])])
print("Matrix Derivative:\n", derivative)

# Example: Gradient
f = x.T * x  # A simple quadratic form
gradient = sp.Matrix([sp.diff(f[0], x[i]) for i in range(x.shape[0])])
print("Gradient:\n", gradient)

# Example: Hessian
hessian = sp.hessian(f[0], x)
print("Hessian:\n", hessian)


[notice] A new release of pip is available: 25.2 -> 26.2.1
[notice] To update, run: pip3 install --upgrade pip
Matrix Derivative:
 Matrix([[2*a11*x1 + a12*x2 + a21*x2], [a12*x1 + a21*x1 + 2*a22*x2]])
Gradient:
 Matrix([[2*x1], [2*x2]])
Hessian:
 Matrix([[2, 0], [0, 2]])
